# Generated by Django 5.2 on 2025-10-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PredictionRecord',
        ),
    ]
